Second Multiband compressor.

The 2nd Multiband compressor can be used in many ways, for example to fine-tune the output of the first, or to add some density.

Because the first [[10461]] can be used in both Analog and Digital mode and this one only supports Analog mode, to keep the descriptions clear, for the first [[10461]] the Digital mode parameters are described, and for this one the Analog parameters are explained.
