Stops the volume from rising when there is (near) silence.

If the input level is very low (noise, silence), raising the output level might cause annoying effects (increasing noise levels during silence, followed by a sudden drop when the sound starts again). When using Gating, if the input level is below the configured [[274]], the gain rise is reduced or stopped ([[29]] and [[30]] are dynamically reduced).
