Adds a controlled amount of distortion, to replicate the sound of certain processors.

Most compressors don't have a clipper that delivers a signal that's as clean and free of distortion as Stereo Tool. Some people (not many...) seem to like this distortion. With Controlled Distortion you can replicate the distortion from those other processors, while still avoiding some really nasty types of distortion.
